### ISSUE TITLE
Could not resolve placeholder 'loda.mysql.url' in value "${loda.mysql.url}"

### ISSUE THREAD

**Issue by equilibrium999** [loda-kun/spring-boot-learning#7]
Mình đang làm theo https://github.com/loda-kun/spring-boot-learning/tree/master/spring-boot-7-spring-application-properties-%40Value

mà khi chạy thì bị lỗi 

`Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'loda.mysql.url' in value "${loda.mysql.url}"
	at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:172) ~[spring-core-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:124) ~[spring-core-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:237) ~[spring-core-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.core.env.AbstractPropertyResolver.resolveRequiredPlaceholders(AbstractPropertyResolver.java:211) ~[spring-core-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.context.support.PropertySourcesPlaceholderConfigurer.lambda$processProperties$0(PropertySourcesPlaceholderConfigurer.java:175) ~[spring-context-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveEmbeddedValue(AbstractBeanFactory.java:839) ~[spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1083) ~[spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1062) ~[spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:583) ~[spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90) ~[spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:372) ~[spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	... 17 common frames omitted
`

Có bạn nào biết sửa lỗi này không?

**Comment by quocnm-py** [comment]
Could you upload your **application.properties** file?
I think you missing field _loda.mysql.url_ in this file.
Try adding following to application.properties:
   `loda.mysql.url=jdbc:mysql://host1:33060/loda`

Reference this [link](https://github.com/loda-kun/spring-boot-learning/tree/master/spring-boot-7-spring-application-properties-%40Value#v%C3%AD-d%E1%BB%A5)

**Comment by equilibrium999** [comment]
Hi, when I clone the file, the field loda.mysql.url is already there.
And even though, I tried with other fields logging.level.root and server.port. It still returns the error  Could not resolve placeholder

`server.port = 8081`
`logging.level.root=INFO`
`loda.mysql.url=jdbc:mysql://host1:33060/loda`

**Comment by quocnm-py** [comment]
> Hi, when I clone the file, the field loda.mysql.url is already there.
> And even though, I tried with other fields logging.level.root and server.port. It still returns the error Could not resolve placeholder
> 
> `server.port = 8081`
> `logging.level.root=INFO`
> `loda.mysql.url=jdbc:mysql://host1:33060/loda`

Send me your compress project for helping you :D
Or you can try [this](https://stackoverflow.com/a/48158753/13678355)

**Comment by equilibrium999** [comment]
hi @quocnm-pyco 
thanks for helping me
PLease find the link attached.
[https://www.mediafire.com/file/fa4hmg8sh2rfx4t/spring-boot-7-spring-application-properties-@Value.zip/file](https://www.mediafire.com/file/fa4hmg8sh2rfx4t/spring-boot-7-spring-application-properties-@Value.zip/file)

**Comment by quocnm-py** [comment]
replace all in your pom.xml by following.

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>2.2.5.RELEASE</version>
    <relativePath/> <!-- lookup parent from repository -->
  </parent>

  <modelVersion>4.0.0</modelVersion>

  <artifactId>spring-boot-7-spring-application-properties</artifactId>

  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter</artifactId>
    </dependency>
  </dependencies>

</project>

```

You run your project independency so use **parent** tag like above and add dependency for springboot.

**Comment by equilibrium999** [comment]
Thanks @quocnm-py 
It's working now.
